version: '3.8'

services:
    web-base-image:
        build:
            context: ./docker-python/base
            args:
                requirements: /root/flask-mongodb-example/python/requirements.txt
        image: web-base

    web-random:
        build:
            context: ./docker-python-pypy
            args:
                requirements: /root/flask-mongodb-example/python/requirements.txt
        image: web-standard-pypy
        ports:
            - "800:5000"
        entrypoint: pypy /root/flask-mongodb-example/python/random_demo.py
        depends_on:
            - mongo

    web-users:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements.txt
        image: web-standard
        ports:
            - "81:5000"
        entrypoint: python /root/flask-mongodb-example/python/users.py
        depends_on:
            - mongo
            - web-base-image

    background-mqtt:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements-mqtt.txt
        image: backgorund-mqtt-image
        entrypoint: python /root/flask-mongodb-example/python/mqtt.py
        environment:
            - MQTT_USER=/run/secrets/mqtt_user
            - MQTT_PASSWORD=/run/secrets/mqtt_password
            - PYTHONUNBUFFERED=1
        secrets:
            - mqtt_user
            - mqtt_password
        depends_on:
            - mongo
            - mqtt
            - influxdb
        tty: true

    web-fulltext-search:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements.txt
        image: web-standard
        ports:
            - "82:5000"
        entrypoint: python /root/flask-mongodb-example/python/fulltext_search.py
        depends_on:
            - mongo

    web-geolocation-search:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements.txt
        image: web-geolocation-image
        ports:
            - "83:5000"
        entrypoint: python /root/flask-mongodb-example/python/geolocation_search.py
        depends_on:
            - mongo

    web-baesian:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements.txt
        image: web-standard
        ports:
            - "84:5000"
        entrypoint: python /root/flask-mongodb-example/python/baesian.py
        depends_on:
            - mongo

    web-photo-process:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements-photo.txt
        image: web-photo-image
        ports:
            - "85:5000"
        entrypoint: python /root/flask-mongodb-example/python/photo_process.py
        volumes:
            - ./container-storage:/root/storage
        depends_on:
            - mongo

    web-book-collection:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements-restplus.txt
        image: web-bookcollection-image
        environment:
             - PYTHONUNBUFFERED=1
        ports:
            - "86:5000"
        entrypoint: python /root/flask-mongodb-example/python/bookcollection.py
        depends_on:
            - mongo
            - web-users

    web-users-fast-api:
        build:
            context: ./docker-python
            args:
                requirements: /root/flask-mongodb-example/python/requirements-fastapi.txt
        image: web-users-fastapi-image
        ports:
            - "88:5000" # port 87 is restricted in browsers
        entrypoint: uvicorn users-fastapi:app --reload --host 0.0.0.0 --port 5000
        depends_on:
            - mongo

    influxdb:
        build: docker-influxdb
        env_file: ./docker-influxdb/configuration.env
        ports:
          - '8086:8086'
        volumes:
          - influxdb_data:/var/lib/influxdb

    grafana:
        build: docker-grafana
        env_file: ./docker-grafana/configuration.env
        links:
          - influxdb
        ports:
          - '3000:3000'
        volumes:
          - grafana_data:/var/lib/grafana

    mongo:
        image: mongo:latest
        hostname: mongodb
        ports:
            - '27017:27017'
        environment:
            - MONGO_REPLICA_SET_NAME=dan
        command:
            - --storageEngine
            - wiredTiger
            - --replSet
            - myrepl

    mqtt:
        build:
          context: ./docker-mosquitto
        ports:
            - "1883:1883"

    krakend:
        image: devopsfaith/krakend
        volumes:
            - ${PWD}/krakend.json:/etc/krakend/krakend.json
        ports:
            - "8080:8080"
        depends_on:
            - web-random
            - web-users

volumes:
    grafana_data: {}
    influxdb_data: {}

secrets:
    mqtt_user:
        file: ./secrets/mqtt_user.txt
    mqtt_password:
        file: ./secrets/mqtt_pass.txt
